[build-wasm]
canister = "joltsample"
did_path = "src/joltsample.did"
cpp_paths = [
    "src/HelloWorld.cpp",
    "./Jolt/*.cpp",
    "./Jolt/*/*.cpp",
    "./Jolt/*/*/*.cpp",
    "./Jolt/*/*/*/*.cpp",
]
cpp_include_dirs = ["Jolt/"]
cpp_compile_flags = [
    "-D JPH_PLATFORM_WASM",
]
cpp_link_flags = []
c_paths = []
c_header_paths = []
c_compile_flags = []
[build-native]
cpp_paths = ["native/main.cpp"]
cpp_include_dirs = []
cpp_compile_flags = []
cpp_link_flags = []
c_paths = []
c_include_dirs = []
c_compile_flags = []
